---
- name: Playbook to install and configure Logstash Service with pipeline
  hosts: all
  vars:
    logstash_pipeline_update: true
    logstash_pipeline_repositories: []
  roles:
    - stone-payments.java
    - stone-payments.logstash
