---
# - name: logstash service with pipeline
#   hosts: group1
#   roles:
#     - stone-payments.java
#     - stone-payments.logstash
#   vars:
#     logstash_enabled_on_boot: yes
#     remove_java: false
#     pipeline_repository:
#       - url: "git@bitbucket.org:stonepayments/ei-logstash-pipelines.git"
#         path: "cerberus-pipeline"

- name: logstash service without pipeline
  hosts: group2
  roles:
    - stone-payments.java
    - stone-payments.logstash
  vars:
    logstash_enabled_on_boot: yes
    remove_java: false
