---
- name: logstash service
  hosts: group1
  roles:
    - buy4.java
    - buy4.logstash
  vars:
    logstash_enabled_on_boot: yes
    remove_java: false
    pipeline_repository:
      - {url: "git@bitbucket.org:stonepayments/ei-logstash-pipelines.git", path: "cerberus-pipeline"}
