---
- name: config | Ensure logstash config dir has right permissions
  file:
    path: "{{ logstash_config_dir }}"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0755
    state: directory

- block:
  - name: config | Create tmp download dir
    local_action: file path={{ downloaded_repos_temp_dir }} state=directory
    become: false

  - name: config | Download pipeline files locally
    local_action: command bash -c "git archive --remote={{ item.url }} HEAD:{{ item.path }} | tar -x -C {{ downloaded_repos_temp_dir }}"
    become: false
    register: result
    changed_when: "result.rc != 0"
    with_items: "{{ pipeline_repository }}"

  - name: config | Get downloaded files
    local_action: find paths="{{ downloaded_repos_temp_dir }}" patterns="*.conf"
    become: false
    register: pipeline_files

  - name: config | Check for files downloaded
    fail:
      msg: "No pipeline files were downloaded"
    when: pipeline_files.files|length == 0

  - name: config | Copy pipeline files
    copy:
      src: "{{ item.path }}"
      dest: "{{ logstash_config_dir }}"
      owner: "{{ logstash_user }}"
      group: "{{ logstash_group }}"
      mode: 0644
    with_items: "{{ pipeline_files.files }}"
    notify: restart logstash

  - name: config | List copied files
    find:
      path: "{{ logstash_config_dir }}"
      patterns: "*.conf"
    register: copied_files

  - name: config | Check if files were copied
    fail:
      msg: "No pipeline files were copied"
    when: copied_files.files|length == 0

  - meta: flush_handlers
  when: force_pipeline_update and pipeline_repository is defined
