---
- name: config | Ensure logstash config dir has right permissions
  file:
    path: "{{ logstash_config_dir }}"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0755
    state: directory

- name: config | Create Logstash inputs.
  copy:
    src: "inputs/{{ item }}"
    dest: "{{ logstash_config_dir }}/{{ item }}"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0644
  with_items: "{{ logstash_input_files | default([]) }}"
  notify: restart logstash

- name: config | Create Logstash filters.
  copy:
    src: "filters/{{ item }}"
    dest: "{{ logstash_config_dir }}/{{ item }}"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0644
  with_items: "{{ logstash_filter_files | default([]) }}"
  notify: restart logstash

- name: config | Create Logstash outputs.
  template:
    src: "{{ item }}"
    dest: "{{ logstash_config_dir }}/{{ item }}"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0644
  with_items: "{{ logstash_output_files | default([]) }}"
  notify: restart logstash
