---
- name: plugins | install logstash plugins
  logstash_plugin:
    name: "{{ item }}"
    state: present
  with_items: "{{ logstash_plugins }}"
  environment:  # workaround for logstash version 5.x
    JAVA_HOME: "{{ logstash_java_home }}"
  notify:
    - restart logstash

- name: plugins | install x-pack plugin
  logstash_plugin:
    name: x-pack
    state: present
  when: logstash_xpack_plugin
  environment:  # workaround for logstash version 5.x
    JAVA_HOME: "{{ logstash_java_home }}"
  notify:
    - restart logstash
