---
- name: plugins | creates folder to logstash plugins
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0755
  with_items: "{{ logstash_path_plugins }}"

- name: plugins | install logstash plugins
  logstash_plugin:
    name: "{{ item }}"
    state: present
  with_items: "{{ logstash_plugins }}"
  environment:  # workaround for logstash version 5.x
    JAVA_HOME: "{{ logstash_java_home }}"
  notify:
    - restart logstash

- name: plugins | install x-pack plugin
  logstash_plugin:
    name: x-pack
    state: present
  when: logstash_xpack_plugin
  environment:  # workaround for logstash version 5.x
    JAVA_HOME: "{{ logstash_java_home }}"
  notify:
    - restart logstash
