---
- name: plugins | install logstash plugins
  logstash_plugin:
    name: "{{ item }}"
    state: present
  with_items: "{{ logstash_plugins }}"
  notify:
    - restart logstash

- name: plugins | install x-pack plugin
  logstash_plugin:
    name: x-pack
    state: present
  when: logstash_xpack_plugin
  notify:
    - restart logstash
