---
- name: setup-RedHat | Add Elasticsearch GPG key.
  rpm_key:
    key: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

- name: setup-RedHat | Add Logstash repository.
  copy:
    src: logstash.repo
    dest: /etc/yum.repos.d/logstash.repo
    mode: 0644

- name: setup-RedHat | Install Logstash.
  yum: pkg=logstash state=installed
