---
- name: setup-Debian | Add Elasticsearch apt key.
  apt_key:
    url: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

- name: setup-Debian | Add Logstash repository.
  apt_repository:
    repo: 'deb http://packages.elasticsearch.org/logstash/2.3/debian stable main'
    state: present

- name: setup-Debian | Check if Logstash is already installed.
  stat: path=/etc/init.d/logstash
  register: logstash_installed

- name: setup-Debian | Update apt cache if repository just added.
  apt: update_cache=yes
  when: logstash_installed.stat.exists == false

- name: setup-Debian | Install Logstash.
  apt: pkg=logstash state=present

- name: setup-Debian | Add Logstash user to adm group (Debian).
  user:
    name: logstash
    group: logstash
    groups: adm
  when: ansible_os_family == "Debian"
  notify: restart logstash
